// Banco de dados local
var detalhes = {
    'Carro Sedan':         { nome: 'Carro Sedan',         ano: 2022, preco: 120000, descricao: 'Sedan confortável e versátil para o dia a dia.',                    vantagens: 'Bom espaço interno e economia de combustível.',           imagem: 'img/carro1.jpg' },
    'Carro SUV':           { nome: 'Carro SUV',           ano: 2021, preco: 180000, descricao: 'SUV robusto e espaçoso, ideal para aventuras.',                          vantagens: 'Amplo espaço e tração 4x4.',                           imagem: 'img/carro2.jpg' },
    'Carro Esportivo':     { nome: 'Carro Esportivo',     ano: 2020, preco: 250000, descricao: 'Desportivo com performance de tirar o fôlego.',                      vantagens: 'Alto desempenho e design arrojado.',                     imagem: 'img/carro3.jpg' },
    'Toyota Corolla':      { nome: 'Toyota Corolla',      ano: 2023, preco: 135000, descricao: 'Sedan com excelente eficiência de combustível e tecnologia avançada.', vantagens: 'Confiabilidade e baixo custo de manutenção.',               imagem: 'img/toyota_corolla.jpg' },
    'Toyota Camry':        { nome: 'Toyota Camry',        ano: 2022, preco: 155000, descricao: 'Sedan elegante com desempenho robusto e conforto excepcional.',       vantagens: 'Conforto, design moderno e alta eficiência.',              imagem: 'img/toyota_camry.jpg' },
    'Honda CR-V':          { nome: 'Honda CR-V',          ano: 2021, preco: 170000, descricao: 'SUV espaçoso com segurança e desempenho de primeira linha.',          vantagens: 'Amplo espaço interno, tecnologia e segurança.',            imagem: 'img/honda_crv.jpg' },
    'Honda Civic':         { nome: 'Honda Civic',         ano: 2022, preco: 140000, descricao: 'Sedan compacto com design esportivo e dirigibilidade ágil.',          vantagens: 'Eficiente, ágil e com bom custo-benefício.',               imagem: 'img/honda_civic.jpg' },
    'Ford Mustang':        { nome: 'Ford Mustang',        ano: 2020, preco: 350000, descricao: 'Esportivo icônico com potência e estilo inconfundíveis.',            vantagens: 'Desempenho e design agressivo.',                         imagem: 'img/FordMustang.png' },
    'Ford Fusion':         { nome: 'Ford Fusion',         ano: 2021, preco: 160000, descricao: 'Sedan confortável com tecnologia moderna, ideal para famílias.',     vantagens: 'Conforto, tecnologia e boa performance.',                imagem: 'img/ford_fusion.jpg' },
    'Jeep Compass':        { nome: 'Jeep Compass',        ano: 2022, preco: 160000, descricao: 'SUV compacto com design robusto e desempenho off-road moderado.',     vantagens: 'Versatilidade e tecnologia embarcada.',                   imagem: 'img/jeep_compass.jpg' },
    'Jeep Renegade':       { nome: 'Jeep Renegade',       ano: 2023, preco: 145000, descricao: 'SUV compacto com estilo diferenciado e ótimo para a cidade.',         vantagens: 'Agilidade urbana e design icônico.',                     imagem: 'img/jeep_renegade.jpg' },
    'Chevrolet Camaro':    { nome: 'Chevrolet Camaro',    ano: 2020, preco: 330000, descricao: 'Esportivo com design agressivo e desempenho impressionante.',         vantagens: 'Performance e estilo marcante.',                        imagem: 'img/chevrolet_camaro.jpg' },
    'Chevrolet Cruze':     { nome: 'Chevrolet Cruze',     ano: 2021, preco: 125000, descricao: 'Sedan compacto com economia de combustível e tecnologia.',           vantagens: 'Eficiência e baixo custo de manutenção.',                imagem: 'img/chevrolet_cruze.jpg' },
    'Audi A4':             { nome: 'Audi A4',             ano: 2021, preco: 240000, descricao: 'Sedan premium com tecnologia avançada e acabamento de luxo.',        vantagens: 'Conforto, tecnologia e design sofisticado.',              imagem: 'img/audi_a4.jpg' },
    'BMW 320i':            { nome: 'BMW 320i',            ano: 2022, preco: 220000, descricao: 'Sedan com performance dinâmica e interior luxuoso.',                 vantagens: 'Desempenho, luxo e tecnologia de ponta.',                 imagem: 'img/bmw_320i.jpg' },
    'Nissan X-Trail':      { nome: 'Nissan X-Trail',      ano: 2022, preco: 190000, descricao: 'SUV versátil com amplo espaço e tecnologia embarcada.',               vantagens: 'Versatilidade, espaço e eficiência.',                     imagem: 'img/nissan_xtrail.jpg' },
    'Nissan Sentra':       { nome: 'Nissan Sentra',       ano: 2023, preco: 130000, descricao: 'Sedan com excelente custo-benefício e conforto para o dia a dia.',   vantagens: 'Econômico, confortável e confiável.',                      imagem: 'img/nissan_sentra.jpg' },
    'Porsche 911':         { nome: 'Porsche 911',         ano: 2021, preco: 950000, descricao: 'Esportivo de alta performance com design icônico.',                vantagens: 'Performance, design e exclusividade.',                    imagem: 'img/porsche_911.jpg' },
    // adicionais ... (BMW X5, M3, i8; Porsche Cayenne, Panamera, Boxster; Audi Q5, A6, TT; Toyota RAV4, Yaris; Honda HR-V, Accord; Ford Explorer, Edge; Jeep Wrangler, Grand Cherokee; Chevrolet Silverado, Tahoe; Nissan Pathfinder, Leaf)
  };